swagger: '2.0'
info:
  title: XSS test
  description: <math><mtext><h1><a><h6></a></h6><mglyph><svg><mtext><textarea><img src=x></textarea></desc></textarea></mtext></mtext></svg></mglyph></option></mtext></math>
  version: production
